### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by goliatone** [IonicaBizau/git-stats#64]
I did not see an uninstall process. What would be the best way to uninstall git-stats?

**Comment by IonicaBizau** [comment]
Just `npm uninstall -g git-stats`–this will uninstall the package. It will not delete the `~/.git-stats` file, just in case you want to move it on another machine or so. If you don't want to do so, just `rm ~/.git-stats`. :fire:

**Comment by goliatone** [comment]
Does git-stats create a git post commit/hooks? Glancing over **init-git-post-commit** it looks like some files are created and/or some global config values are created- like changing the **templates** directory. Are you saying that `npm uninstall` is taking care of those?

**Comment by IonicaBizau** [comment]
Ahh, that's a good point–it will *not* remove the hooks. Removing the hooks from `~/.git-templates` will not solve the problem. You will most probably need to `rm .git/hooks/post-commit` in each git repository, otherwise you will get ugly errors after you commit things.

**Comment by auremoser** [comment]
+1 this is an issue for me too. It appears to directly conflict with [gistup](https://github.com/mbostock/gistup) for reasons I'm not sure how to troubleshoot. 

so perhaps there is no way to fix the conflict i'm currently seeing in my repos when i try to `gistup` in a directory. 

```
$ gistup --public -m 'Testing stuff'
```
and it fails with this error:
```
Reinitialized existing Git repository in /Users/auremoser/code/2015/gist-test/.git/
error Error: Invalid url field. This commit is not recorded into the git-stats history since you haven't added the remote url. You can import the previous commits using the git-stats-importer tool.

/usr/local/lib/node_modules/gistup/lib/gistup/unless.js:11
    throw error;
          ^
Error: git commit failed.
    at /usr/local/lib/node_modules/gistup/bin/gistup:152:65
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```
I documented it in this issue too [#23](https://github.com/mbostock/gistup/issues/23), but it doesn't seem to be an issue on the gistup end. :(

**Comment by IonicaBizau** [comment]
Hey @auremoser! This seems to be related, but a different issue–if I'm not wrong, this is already fixed in the `2.0.0` branch. To install the latest version (not yet merged into master, but kind of stable: see #47), do:

```sh
$ npm i ionicabizau/git-stats#v2.0.0
```

The remote url is not required anymore, so this should work in your case. :four_leaf_clover: Can you confirm?

**Comment by auremoser** [comment]
Thank you  for responding! It still doesn't work post-install of the new version, but now the error is different and more specific...progress!

```
$ gistup --public -m 'Testing stuff'
```

```
error Error: Invalid url field. This commit is not recorded into the git-stats history since you haven't added the remote url. You can import the previous commits using the git-stats-importer tool.

/usr/local/lib/node_modules/gistup/lib/gistup/unless.js:11
    throw error;
          ^
Error: git commit failed.
    at /usr/local/lib/node_modules/gistup/bin/gistup:152:65
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

If there is a way to avoid [this error throw](https://github.com/mbostock/gistup/blob/master/lib/gistup/unless.js) or you have any other tips (for uninstallation or whatever else), I'd love to read them. Gistup has been in my workflow for a while now, and it would be awesome to get it working again.

**Comment by IonicaBizau** [comment]
Isn't the error the same?

Please give me the output of `git-stats -v`–thanks! :smile_cat:

**Comment by auremoser** [comment]
oof good point. 

I ran your install and got this, which looked fine.
```
|
> git-stats@2.0.0 postinstall /Users/aurelia/node_modules/git-stats
> ./scripts/migration/2.0.0.js

git-stats@2.0.0 ../../../node_modules/git-stats
├── abs@1.0.0
├── deffy@2.0.0
├── progress@1.1.8
├── r-json@1.0.0
├── w-json@1.1.0
├── typpy@2.0.0
├── ul@5.0.0
├── is-there@4.0.0
├── moment@2.10.6
├── gry@4.0.0 (one-by-one@2.0.0, exec-limiter@2.0.0)
├── bug-killer@4.0.0 (ansi-parser@3.0.0, couleurs@5.0.0)
├── cli-gh-cal@1.0.0 (git-stats-colors@2.1.0, cli-box@5.0.0, ansi-parser@3.0.0, couleurs@5.0.0)
├── gitlog-parser@0.0.4 (byline@4.2.1)
├── clp@3.0.0 (ansi-parser@2.0.0, le-table@4.0.0)
└── cli-pie@2.0.0 (flatcolors@3.0.0, couleurs@5.0.0, cli-circle@3.0.0)
```
but then,
```
git-stats -v
```
```
1.6.0
```
should it be 2.0?

**Comment by IonicaBizau** [comment]
Ha! Actually I was wrong! :smile: You should install it globally:

```sh
npm i -g ionicabizau/git-stats#v2.0.0
```

(in my previous comment the `-g` is missing)

Sorry! :cake:

**Comment by auremoser** [comment]
huzzah! it [worked](https://gist.github.com/auremoser/1f2e4d564dc84a6ab507) :)
¡gracias!

**Comment by IonicaBizau** [comment]
Aww, cool! :smile: :tada:
